import { BrowserContext, expect, test } from "@playwright/test"

async function getUserIdFromCookies(context: BrowserContext): Promise<string> {
  const cookies = await context.cookies()
  const tokenCookie = cookies.find((c) => c.name === "access_token")
  if (!tokenCookie) {
    throw new Error("access_token cookie not found")
  }
  const payloadBase64 = tokenCookie.value.split(".")[1]
  const payloadJson = Buffer.from(payloadBase64, "base64").toString("utf-8")
  const payload = JSON.parse(payloadJson) as { sub: number | string }
  return String(payload.sub)
}

test.describe("CV Projects page - admin", () => {
  test.use({ storageState: "playwright/.auth/admin.json" })

  test.describe("Own CV Projects", () => {
    test.beforeEach(async ({ page, context }) => {
      const userId = await getUserIdFromCookies(context)
      await page.goto(`/users/${userId}/cvs`)
      const table = page.getByTestId("cvs-table")
      await expect(table).toBeVisible()

      // Setup: Check if admin has at least one CV
      const adminEmail = "admin@test.com"
      const hasOwnCv =
        (await table.locator("tr", { hasText: adminEmail }).count()) > 0

      if (!hasOwnCv) {
        const createBtn = page.getByTestId("create-cv-button")
        await expect(createBtn).toBeVisible()
        await page.waitForTimeout(1000)
        await createBtn.click()
        await expect(page.getByRole("dialog")).toBeVisible()

        await page.locator('input[id="name"]').fill("Autogenerated Admin CV")
        await page
          .locator('input[id="education"]')
          .fill("Autogenerated Education")
        await page
          .locator('textarea[id="description"]')
          .fill("Autogenerated Description")
        await page.getByTestId("dialog-submit-button").click()

        // Wait for success toast
        const successToast = page
          .locator("[data-sonner-toast] [data-title]")
          .filter({ hasText: "CV created successfully!" })
        await expect(successToast).toBeVisible()
        await expect(page.getByRole("dialog")).toBeHidden()
      }

      // Navigate to the own CV's projects page via details tab
      const ownRow = page.locator("tr").filter({ hasText: adminEmail }).first()
      await expect(ownRow).toBeVisible()
      await page.waitForTimeout(1000)
      await ownRow.getByTestId("row-actions-trigger").click()
      await page.getByTestId("row-action-view").click()
      await expect(page).toHaveURL(/\/cvs\/.+/)

      // Click Projects tab
      await page
        .getByRole("main")
        .getByRole("link", { name: "Projects" })
        .click()
      await expect(page).toHaveURL(/\/cvs\/.+\/projects/)
    })

    test("Admin should be able to add projects to their own CV", async ({
      page,
    }) => {
      // 1. Add first project with responsibilities
      const addBtn = page.getByTestId("add-cv-project-button")
      await expect(addBtn).toBeVisible()
      await addBtn.click()

      await expect(page.getByRole("dialog")).toBeVisible()

      await page.getByTestId("project-select").click()

      const firstOption = page.locator("role=option").first()
      await expect(firstOption).toBeVisible()
      const firstProjectName = (await firstOption.textContent())?.trim()
      if (!firstProjectName) {
        throw new Error("No available projects to add in Combobox")
      }
      await firstOption.click()

      const respInput = page.locator('input[id="responsibilities"]')
      await expect(respInput).toBeVisible()
      await respInput.fill("Architecture design")
      await respInput.press("Enter")
      await respInput.fill("Team leading")
      await respInput.press("Enter")

      await page.getByTestId("dialog-submit-button").click()

      const successToast = page
        .locator("[data-sonner-toast] [data-title]")
        .filter({ hasText: "Project added successfully!" })
        .first()
      await expect(successToast).toBeVisible()
      await expect(page.getByRole("dialog")).toBeHidden()

      const addedRow = page
        .locator("tr")
        .filter({ hasText: firstProjectName })
        .first()
      await expect(addedRow).toBeVisible()
      const subRow = addedRow.locator("+ tr")
      await expect(
        subRow.locator("span", { hasText: "Architecture design" })
      ).toBeVisible()
      await expect(
        subRow.locator("span", { hasText: "Team leading" })
      ).toBeVisible()

      // 2. Add second project without responsibilities
      await addBtn.click()
      await expect(page.getByRole("dialog")).toBeVisible()

      await page.getByTestId("project-select").click()

      const secondOption = page.locator("role=option").first()
      await expect(secondOption).toBeVisible()
      const secondProjectName = (await secondOption.textContent())?.trim()
      if (!secondProjectName) {
        throw new Error("No available second project to add in Combobox")
      }
      await secondOption.click()

      await page.getByTestId("dialog-submit-button").click()

      const successToast2 = page
        .locator("[data-sonner-toast] [data-title]")
        .filter({ hasText: "Project added successfully!" })
        .first()
      await expect(successToast2).toBeVisible()
      await expect(page.getByRole("dialog")).toBeHidden()

      const addedRow2 = page
        .locator("tr")
        .filter({ hasText: secondProjectName })
        .first()
      await expect(addedRow2).toBeVisible()
    })
  })

  test.describe("Employee CV Projects", () => {
    test.beforeEach(async ({ page }) => {
      // Navigate to global CVs list
      await page.goto("/cvs")
      const table = page.getByTestId("cvs-table")
      await expect(table).toBeVisible()

      // Locate an employee's CV row (non-admin)
      let employeeRow = page.locator("tbody tr").first()
      if (
        (await employeeRow.locator("td").nth(3).textContent())?.trim() ===
        "admin@test.com"
      ) {
        employeeRow = page.locator("tbody tr").nth(1)
      }
      await expect(employeeRow).toBeVisible()
      await page.waitForTimeout(1000)

      // Click actions trigger and then click View
      await employeeRow.getByTestId("row-actions-trigger").click()
      await page.getByTestId("row-action-view").click()
      await expect(page).toHaveURL(/\/cvs\/.+/)

      // Click Projects tab
      await page
        .getByRole("main")
        .getByRole("link", { name: "Projects" })
        .click()
      await expect(page).toHaveURL(/\/cvs\/.+\/projects/)
    })

    test("Admin should be able to add projects to employee's CV", async ({
      page,
    }) => {
      // 1. Add first project with responsibilities
      const addBtn = page.getByTestId("add-cv-project-button")
      await expect(addBtn).toBeVisible()
      await addBtn.click()

      await expect(page.getByRole("dialog")).toBeVisible()

      await page.getByTestId("project-select").click()

      const firstOption = page.locator("role=option").first()
      await expect(firstOption).toBeVisible()
      const firstProjectName = (await firstOption.textContent())?.trim()
      if (!firstProjectName) {
        throw new Error("No available projects to add in Combobox")
      }
      await firstOption.click()

      const respInput = page.locator('input[id="responsibilities"]')
      await expect(respInput).toBeVisible()
      await respInput.fill("Code review")
      await respInput.press("Enter")
      await respInput.fill("Mentoring")
      await respInput.press("Enter")

      await page.getByTestId("dialog-submit-button").click()

      const successToast = page
        .locator("[data-sonner-toast] [data-title]")
        .filter({ hasText: "Project added successfully!" })
        .first()
      await expect(successToast).toBeVisible()
      await expect(page.getByRole("dialog")).toBeHidden()

      const addedRow = page
        .locator("tr")
        .filter({ hasText: firstProjectName })
        .first()
      await expect(addedRow).toBeVisible()
      const subRow = addedRow.locator("+ tr")
      await expect(
        subRow.locator("span", { hasText: "Code review" })
      ).toBeVisible()
      await expect(
        subRow.locator("span", { hasText: "Mentoring" })
      ).toBeVisible()

      // 2. Add second project without responsibilities
      await addBtn.click()
      await expect(page.getByRole("dialog")).toBeVisible()

      await page.getByTestId("project-select").click()

      const secondOption = page.locator("role=option").first()
      await expect(secondOption).toBeVisible()
      const secondProjectName = (await secondOption.textContent())?.trim()
      if (!secondProjectName) {
        throw new Error("No available second project to add in Combobox")
      }
      await secondOption.click()

      await page.getByTestId("dialog-submit-button").click()

      const successToast2 = page
        .locator("[data-sonner-toast] [data-title]")
        .filter({ hasText: "Project added successfully!" })
        .first()
      await expect(successToast2).toBeVisible()
      await expect(page.getByRole("dialog")).toBeHidden()

      const addedRow2 = page
        .locator("tr")
        .filter({ hasText: secondProjectName })
        .first()
      await expect(addedRow2).toBeVisible()
    })
  })
})
