import { BrowserContext, expect, test } from "@playwright/test"

async function getUserIdFromCookies(context: BrowserContext): Promise<string> {
  const cookies = await context.cookies()
  const tokenCookie = cookies.find((c) => c.name === "access_token")
  if (!tokenCookie) {
    throw new Error("access_token cookie not found")
  }
  const payloadBase64 = tokenCookie.value.split(".")[1]
  const payloadJson = Buffer.from(payloadBase64, "base64").toString("utf-8")
  const payload = JSON.parse(payloadJson) as { sub: number | string }
  return String(payload.sub)
}

test.describe("CV Projects page - employee", () => {
  test.use({ storageState: "playwright/.auth/user.json" })

  test.describe("Own CV Projects", () => {
    test.beforeEach(async ({ page, context }) => {
      const userId = await getUserIdFromCookies(context)
      await page.goto(`/users/${userId}/cvs`)
      const table = page.getByTestId("cvs-table")
      await expect(table).toBeVisible()

      // Setup: Check if employee has at least one CV
      const employeeEmail = "employee@test.com"
      const hasOwnCv =
        (await table.locator("tr", { hasText: employeeEmail }).count()) > 0

      if (!hasOwnCv) {
        const createBtn = page.getByTestId("create-cv-button")
        await expect(createBtn).toBeVisible()
        await page.waitForTimeout(1000)
        await createBtn.click()
        await expect(page.getByRole("dialog")).toBeVisible()

        await page.locator('input[id="name"]').fill("Autogenerated Employee CV")
        await page
          .locator('input[id="education"]')
          .fill("Autogenerated Education")
        await page
          .locator('textarea[id="description"]')
          .fill("Autogenerated Description")
        await page.getByTestId("dialog-submit-button").click()

        // Wait for success toast
        const successToast = page
          .locator("[data-sonner-toast] [data-title]")
          .filter({ hasText: "CV created successfully!" })
        await expect(successToast).toBeVisible()
        await expect(page.getByRole("dialog")).toBeHidden()
      }

      // Navigate to the own CV's projects page via details tab
      const ownRow = page
        .locator("tr")
        .filter({ hasText: employeeEmail })
        .first()
      await expect(ownRow).toBeVisible()
      await page.waitForTimeout(1000)
      await ownRow.getByTestId("row-actions-trigger").click()
      await page.getByTestId("row-action-view").click()
      await expect(page).toHaveURL(/\/cvs\/.+/)

      // Click Projects tab
      await page
        .getByRole("main")
        .getByRole("link", { name: "Projects" })
        .click()
      await expect(page).toHaveURL(/\/cvs\/.+\/projects/)
    })

    test("Should be able to add a project with responsibilities and another without responsibilities", async ({
      page,
    }) => {
      // 1. Add first project with responsibilities
      const addBtn = page.getByTestId("add-cv-project-button")
      await expect(addBtn).toBeVisible()
      await addBtn.click()

      await expect(page.getByRole("dialog")).toBeVisible()

      // Click project select combobox
      await page.getByTestId("project-select").click()

      // Get first available option
      const firstOption = page.locator("role=option").first()
      await expect(firstOption).toBeVisible()
      const firstProjectName = (await firstOption.textContent())?.trim()
      if (!firstProjectName) {
        throw new Error("No available projects to add in Combobox")
      }
      await firstOption.click()

      // Type responsibilities
      const respInput = page.locator('input[id="responsibilities"]')
      await expect(respInput).toBeVisible()
      await respInput.fill("Developing frontend components")
      await respInput.press("Enter")
      await respInput.fill("Writing E2E tests")
      await respInput.press("Enter")

      // Submit
      await page.getByTestId("dialog-submit-button").click()

      // Wait for success toast
      const successToast = page
        .locator("[data-sonner-toast] [data-title]")
        .filter({ hasText: "Project added successfully!" })
        .first()
      await expect(successToast).toBeVisible()
      await expect(page.getByRole("dialog")).toBeHidden()

      // Verify the added project row and its responsibilities are visible
      const addedRow = page
        .locator("tr")
        .filter({ hasText: firstProjectName })
        .first()
      await expect(addedRow).toBeVisible()
      const subRow = addedRow.locator("+ tr")
      await expect(
        subRow.locator("span", { hasText: "Developing frontend components" })
      ).toBeVisible()
      await expect(
        subRow.locator("span", { hasText: "Writing E2E tests" })
      ).toBeVisible()

      // 2. Add second project without responsibilities
      await addBtn.click()
      await expect(page.getByRole("dialog")).toBeVisible()

      // Click project select combobox
      await page.getByTestId("project-select").click()

      // Get next available option
      const secondOption = page.locator("role=option").first()
      await expect(secondOption).toBeVisible()
      const secondProjectName = (await secondOption.textContent())?.trim()
      if (!secondProjectName) {
        throw new Error("No available second project to add in Combobox")
      }
      await secondOption.click()

      // Submit directly without adding responsibilities
      await page.getByTestId("dialog-submit-button").click()

      // Wait for success toast
      const successToast2 = page
        .locator("[data-sonner-toast] [data-title]")
        .filter({ hasText: "Project added successfully!" })
        .first()
      await expect(successToast2).toBeVisible()
      await expect(page.getByRole("dialog")).toBeHidden()

      // Verify the second project row is visible
      const addedRow2 = page
        .locator("tr")
        .filter({ hasText: secondProjectName })
        .first()
      await expect(addedRow2).toBeVisible()
    })
  })

  test.describe("Other CV Projects", () => {
    test("Should restrict employee from modifying another user's CV projects", async ({
      page,
      context,
    }) => {
      const userId = await getUserIdFromCookies(context)
      const otherUserId = userId === "630" ? "629" : "630"
      await page.goto(`/users/${otherUserId}/cvs`)
      await expect(page.getByTestId("cvs-table")).toBeVisible()

      const directViewLink = page.getByTestId("row-direct-view").first()

      if (await directViewLink.isVisible()) {
        await directViewLink.click()
        await expect(page).toHaveURL(/\/cvs\/.+/)

        // Click Projects tab
        await page
          .getByRole("main")
          .getByRole("link", { name: "Projects" })
          .click()
        await expect(page).toHaveURL(/\/cvs\/.+\/projects/)

        // Verify actions buttons are hidden
        await expect(page.getByTestId("add-cv-project-button")).toBeHidden()
      }
    })
  })
})
