import { expect, test } from "@playwright/test"

test.describe("Global CVs page - admin", () => {
  test.use({ storageState: "playwright/.auth/admin.json" })

  test.beforeEach(async ({ page }) => {
    await page.goto("/cvs")
    const table = page.getByTestId("cvs-table")
    await expect(table).toBeVisible()

    // Setup: Check if admin has at least one CV in the list
    const adminEmail = "admin@test.com"
    const hasOwnCv =
      (await table.locator("tr", { hasText: adminEmail }).count()) > 0

    if (!hasOwnCv) {
      const createBtn = page.getByTestId("create-cv-button")
      await expect(createBtn).toBeVisible()
      await page.waitForTimeout(1000)
      await createBtn.click()
      await expect(page.getByRole("dialog")).toBeVisible()

      await page.locator('input[id="name"]').fill("Autogenerated Admin CV")
      await page
        .locator('input[id="education"]')
        .fill("Autogenerated Education")
      await page
        .locator('textarea[id="description"]')
        .fill("Autogenerated Description")
      await page.getByTestId("dialog-submit-button").click()

      // Wait for success toast
      const successToast = page
        .locator("[data-sonner-toast] [data-title]")
        .filter({ hasText: "CV created successfully!" })
      await expect(successToast).toBeVisible()
      await expect(page.getByRole("dialog")).toBeHidden()
    }
  })

  test("Admin should be able to manage any CV", async ({ page }) => {
    const table = page.getByTestId("cvs-table")
    const rows = table.locator("tbody tr")
    const count = await rows.count()

    // 1. Verify that every row has the actions trigger and no direct-view links
    for (let i = 0; i < count; i++) {
      const row = rows.nth(i)
      // If it is not a "No results" empty table placeholder row
      if ((await row.locator("td").count()) > 1) {
        await expect(row.getByTestId("row-actions-trigger")).toBeVisible()
        await expect(row.getByTestId("row-direct-view")).not.toBeAttached()
      }
    }

    // 2. Locate any employee's CV row (non-admin) on page 1 to test administrative management
    let employeeRow = page.locator("tbody tr").first()
    if (
      (await employeeRow.locator("td").nth(3).textContent())?.trim() ===
      "admin@test.com"
    ) {
      employeeRow = page.locator("tbody tr").nth(1)
    }
    await expect(employeeRow).toBeVisible()

    const actionsTrigger = employeeRow.getByTestId("row-actions-trigger")
    await expect(actionsTrigger).toBeVisible()

    // Click trigger and verify actions are visible
    await actionsTrigger.click()
    await expect(page.getByTestId("row-action-view")).toBeVisible()
    await expect(page.getByTestId("row-action-edit")).toBeVisible()
    await expect(page.getByTestId("row-action-delete")).toBeVisible()

    // Click edit and verify update dialog opens
    await page.getByTestId("row-action-edit").click()
    await expect(page.getByRole("dialog")).toBeVisible()

    // Close the dialog
    await page.getByTestId("dialog-cancel-button").click()
    await expect(page.getByRole("dialog")).toBeHidden()
  })
})
