import { expect, test } from "@playwright/test"

test.describe("Global CVs page - employee", () => {
  test.use({ storageState: "playwright/.auth/user.json" })

  test.beforeEach(async ({ page }) => {
    await page.goto("/cvs")
    const table = page.getByTestId("cvs-table")
    await expect(table).toBeVisible()

    // Setup: Check if employee has at least one CV in the list
    const employeeEmail = "employee@test.com"
    const hasOwnCv =
      (await table.locator("tr", { hasText: employeeEmail }).count()) > 0

    if (!hasOwnCv) {
      const createBtn = page.getByTestId("create-cv-button")
      await expect(createBtn).toBeVisible()
      await page.waitForTimeout(1000)
      await createBtn.click()
      await expect(page.getByRole("dialog")).toBeVisible()

      await page.locator('input[id="name"]').fill("Autogenerated Employee CV")
      await page
        .locator('input[id="education"]')
        .fill("Autogenerated Education")
      await page
        .locator('textarea[id="description"]')
        .fill("Autogenerated Description")
      await page.getByTestId("dialog-submit-button").click()

      // Wait for success toast
      const successToast = page
        .locator("[data-sonner-toast] [data-title]")
        .filter({ hasText: "CV created successfully!" })
      await expect(successToast).toBeVisible()
      await expect(page.getByRole("dialog")).toBeHidden()
    }
  })

  test("Employee should be able to manage their own CV", async ({ page }) => {
    const ownRow = page
      .locator("tr")
      .filter({ hasText: "employee@test.com" })
      .first()
    await expect(ownRow).toBeVisible()

    // Verify row actions trigger button is present
    const actionsTrigger = ownRow.getByTestId("row-actions-trigger")
    await expect(actionsTrigger).toBeVisible()

    // Click trigger and verify actions are visible
    await actionsTrigger.click()
    await expect(page.getByTestId("row-action-view")).toBeVisible()
    await expect(page.getByTestId("row-action-edit")).toBeVisible()
    await expect(page.getByTestId("row-action-delete")).toBeVisible()

    // Click edit and verify update dialog opens
    await page.getByTestId("row-action-edit").click()
    await expect(page.getByRole("dialog")).toBeVisible()

    // Close the dialog
    await page.getByTestId("dialog-cancel-button").click()
    await expect(page.getByRole("dialog")).toBeHidden()
  })

  test("Employee should only have read-only access to others' CVs", async ({
    page,
  }) => {
    // Locate the first direct-view link representing another user's CV (read-only)
    const directViewLink = page.getByTestId("row-direct-view").first()

    if (await directViewLink.isVisible()) {
      // Find its parent row and verify it does NOT have row-actions-trigger
      const parentRow = page
        .locator("tr")
        .filter({ has: directViewLink })
        .first()
      await expect(
        parentRow.getByTestId("row-actions-trigger")
      ).not.toBeAttached()

      // Click direct view and verify read-only details page
      await directViewLink.click()
      await expect(page).toHaveURL(/\/cvs\/.+/)

      // Verify fields are read-only
      await expect(page.locator('input[id="name"]')).toHaveAttribute(
        "readonly",
        ""
      )
      await expect(page.locator('input[id="education"]')).toHaveAttribute(
        "readonly",
        ""
      )
      await expect(page.locator('textarea[id="description"]')).toHaveAttribute(
        "readonly",
        ""
      )

      // Verify Update button is not visible
      const updateBtn = page
        .locator('button[type="submit"]')
        .filter({ hasText: "Update" })
      await expect(updateBtn).toBeHidden()
    }
  })
})
