import { BrowserContext, expect, test } from "@playwright/test"

async function getUserIdFromCookies(context: BrowserContext): Promise<string> {
  const cookies = await context.cookies()
  const tokenCookie = cookies.find((c) => c.name === "access_token")
  if (!tokenCookie) {
    throw new Error("access_token cookie not found")
  }
  const payloadBase64 = tokenCookie.value.split(".")[1]
  const payloadJson = Buffer.from(payloadBase64, "base64").toString("utf-8")
  const payload = JSON.parse(payloadJson) as { sub: number | string }
  return String(payload.sub)
}

test.describe("CV Skills page - employee", () => {
  test.use({ storageState: "playwright/.auth/user.json" })

  test.describe("Own CV Skills", () => {
    test.beforeEach(async ({ page, context }) => {
      const userId = await getUserIdFromCookies(context)
      await page.goto(`/users/${userId}/cvs`)
      const table = page.getByTestId("cvs-table")
      await expect(table).toBeVisible()

      // Setup: Check if employee has at least one CV
      const employeeEmail = "employee@test.com"
      const hasOwnCv =
        (await table.locator("tr", { hasText: employeeEmail }).count()) > 0

      if (!hasOwnCv) {
        const createBtn = page.getByTestId("create-cv-button")
        await expect(createBtn).toBeVisible()
        await page.waitForTimeout(1000)
        await createBtn.click()
        await expect(page.getByRole("dialog")).toBeVisible()

        await page.locator('input[id="name"]').fill("Autogenerated Employee CV")
        await page
          .locator('input[id="education"]')
          .fill("Autogenerated Education")
        await page
          .locator('textarea[id="description"]')
          .fill("Autogenerated Description")
        await page.getByTestId("dialog-submit-button").click()

        // Wait for success toast
        const successToast = page
          .locator("[data-sonner-toast] [data-title]")
          .filter({ hasText: "CV created successfully!" })
        await expect(successToast).toBeVisible()
        await expect(page.getByRole("dialog")).toBeHidden()
      }

      // Navigate to the own CV's skills page via details tab
      const ownRow = page
        .locator("tr")
        .filter({ hasText: employeeEmail })
        .first()
      await expect(ownRow).toBeVisible()
      await ownRow.getByTestId("row-actions-trigger").click()
      await page.getByTestId("row-action-view").click()
      await expect(page).toHaveURL(/\/cvs\/.+/)

      // Click Skills tab
      await page.getByRole("main").getByRole("link", { name: "Skills" }).click()
      await expect(page).toHaveURL(/\/cvs\/.+\/skills/)
    })

    test("Should be able to add, edit, and delete a skill on their own CV", async ({
      page,
    }) => {
      // 1. Initial State Check
      const addBtn = page.getByTestId("add-skill-button")
      await expect(addBtn).toBeVisible()

      const removeBtn = page.getByTestId("remove-skills-button")
      const skillCards = page.locator('[data-testid^="skill-item-"]')
      const initialSkillCount = await skillCards.count()

      if (initialSkillCount === 0) {
        await expect(removeBtn).toBeHidden()
      } else {
        await expect(removeBtn).toBeVisible()
      }

      // 2. Add a new skill
      await addBtn.click()
      await expect(page.getByRole("dialog")).toBeVisible()

      await page.getByTestId("skill-select").click()

      // Get first available option
      const firstOption = page.locator("role=option").first()
      await expect(firstOption).toBeVisible()
      const targetSkill = (await firstOption.textContent())?.trim()
      if (!targetSkill) {
        throw new Error("No available skills to add in Combobox")
      }
      await firstOption.click()

      await page.getByTestId("skill-mastery-select").click()
      await page.locator('role=option[name="Novice"]').click()

      await page.getByTestId("dialog-submit-button").click()

      // Wait for success toast
      const successToast = page
        .locator("[data-sonner-toast] [data-title]")
        .filter({ hasText: "Skill was added" })
      await expect(successToast).toBeVisible()
      await expect(page.getByRole("dialog")).toBeHidden()

      // 3. Edit the skill
      const addedSkillCard = page.getByTestId(`skill-item-${targetSkill}`)
      await expect(addedSkillCard).toBeVisible()
      await addedSkillCard.click()

      await expect(page.getByRole("dialog")).toBeVisible()

      await page.getByTestId("skill-mastery-select").click()
      await page.locator('role=option[name="Proficient"]').click()

      await page.getByTestId("dialog-submit-button").click()

      // Wait for success toast
      const updateToast = page
        .locator("[data-sonner-toast] [data-title]")
        .filter({ hasText: "Skill was updated" })
      await expect(updateToast).toBeVisible()
      await expect(page.getByRole("dialog")).toBeHidden()

      // 4. Select skill and delete
      const removeBtnNow = page.getByTestId("remove-skills-button")
      await expect(removeBtnNow).toBeVisible()
      await removeBtnNow.click()

      await addedSkillCard.click()

      const confirmDeleteBtn = page.getByTestId("confirm-delete-button")
      await expect(confirmDeleteBtn).toBeEnabled()
      await confirmDeleteBtn.click()

      // Wait for success toast
      const deleteToast = page
        .locator("[data-sonner-toast] [data-title]")
        .filter({ hasText: "Skill was removed" })
      await expect(deleteToast).toBeVisible()

      await expect(addedSkillCard).toBeHidden()
    })
  })

  test.describe("Other CV Skills", () => {
    test("Should restrict employee from modifying another user's CV skills", async ({
      page,
      context,
    }) => {
      const userId = await getUserIdFromCookies(context)
      const otherUserId = userId === "630" ? "629" : "630"
      await page.goto(`/users/${otherUserId}/cvs`)
      await expect(page.getByTestId("cvs-table")).toBeVisible()

      // Locate first CV in other user's list (which will be read-only direct view)
      const directViewLink = page.getByTestId("row-direct-view").first()

      if (await directViewLink.isVisible()) {
        await directViewLink.click()
        await expect(page).toHaveURL(/\/cvs\/.+/)

        // Click Skills tab
        await page
          .getByRole("main")
          .getByRole("link", { name: "Skills" })
          .click()
        await expect(page).toHaveURL(/\/cvs\/.+\/skills/)

        // Verify actions buttons are hidden
        await expect(page.getByTestId("add-skill-button")).toBeHidden()
        await expect(page.getByTestId("remove-skills-button")).toBeHidden()

        // Verify skill items are disabled if they exist
        const skillCards = page.locator('[data-testid^="skill-item-"]')
        const count = await skillCards.count()
        for (let i = 0; i < count; i++) {
          await expect(skillCards.nth(i)).toBeDisabled()
        }
      }
    })
  })
})
