import { BrowserContext, expect, test } from "@playwright/test"

async function getUserIdFromCookies(context: BrowserContext): Promise<string> {
  const cookies = await context.cookies()
  const tokenCookie = cookies.find((c) => c.name === "access_token")
  if (!tokenCookie) {
    throw new Error("access_token cookie not found")
  }
  const payloadBase64 = tokenCookie.value.split(".")[1]
  const payloadJson = Buffer.from(payloadBase64, "base64").toString("utf-8")
  const payload = JSON.parse(payloadJson) as { sub: number | string }
  return String(payload.sub)
}

test.describe("CV Preview page - admin", () => {
  test.use({ storageState: "playwright/.auth/admin.json" })

  test.describe("Own CV Preview", () => {
    test.beforeEach(async ({ page, context }) => {
      const userId = await getUserIdFromCookies(context)
      await page.goto(`/users/${userId}/cvs`)
      const table = page.getByTestId("cvs-table")
      await expect(table).toBeVisible()

      // Setup: Check if admin has at least one CV
      const adminEmail = "admin@test.com"
      const hasOwnCv =
        (await table.locator("tr", { hasText: adminEmail }).count()) > 0

      if (!hasOwnCv) {
        const createBtn = page.getByTestId("create-cv-button")
        await expect(createBtn).toBeVisible()
        await page.waitForTimeout(1000)
        await createBtn.click()
        await expect(page.getByRole("dialog")).toBeVisible()

        await page.locator('input[id="name"]').fill("Autogenerated Admin CV")
        await page
          .locator('input[id="education"]')
          .fill("Autogenerated Education")
        await page
          .locator('textarea[id="description"]')
          .fill("Autogenerated Description")
        await page.getByTestId("dialog-submit-button").click()

        // Wait for success toast
        const successToast = page
          .locator("[data-sonner-toast] [data-title]")
          .filter({ hasText: "CV created successfully!" })
        await expect(successToast).toBeVisible()
        await expect(page.getByRole("dialog")).toBeHidden()
      }

      // Navigate to own CV's preview page via details tab
      const ownRow = page.locator("tr").filter({ hasText: adminEmail }).first()
      await expect(ownRow).toBeVisible()
      await page.waitForTimeout(1000)
      await ownRow.getByTestId("row-actions-trigger").click()
      await page.getByTestId("row-action-view").click()
      await expect(page).toHaveURL(/\/cvs\/.+/)

      // Click Preview tab
      await page
        .getByRole("main")
        .getByRole("link", { name: "Preview" })
        .click()
      await expect(page).toHaveURL(/\/cvs\/.+\/preview/)
    })

    test("Admin should be able to view and download own CV PDF", async ({
      page,
    }) => {
      await expect(page.locator("#cv-preview")).toBeVisible()

      const exportBtn = page.getByTestId("export-pdf-button")
      await expect(exportBtn).toBeVisible()

      const downloadPromise = page.waitForEvent("download")
      await exportBtn.click()
      const download = await downloadPromise

      expect(download.suggestedFilename()).toContain("CV")
    })
  })

  test.describe("Employee CV Preview", () => {
    test.beforeEach(async ({ page }) => {
      // Navigate to global CVs list
      await page.goto("/cvs")
      const table = page.getByTestId("cvs-table")
      await expect(table).toBeVisible()

      // Locate an employee's CV row (non-admin)
      let employeeRow = page.locator("tbody tr").first()
      if (
        (await employeeRow.locator("td").nth(3).textContent())?.trim() ===
        "admin@test.com"
      ) {
        employeeRow = page.locator("tbody tr").nth(1)
      }
      await expect(employeeRow).toBeVisible()
      await page.waitForTimeout(1000)

      // Click actions trigger and click View
      await employeeRow.getByTestId("row-actions-trigger").click()
      await page.getByTestId("row-action-view").click()
      await expect(page).toHaveURL(/\/cvs\/.+/)

      // Click Preview tab
      await page
        .getByRole("main")
        .getByRole("link", { name: "Preview" })
        .click()
      await expect(page).toHaveURL(/\/cvs\/.+\/preview/)
    })

    test("Admin should be able to view and download employee's CV PDF", async ({
      page,
    }) => {
      await expect(page.locator("#cv-preview")).toBeVisible()

      const exportBtn = page.getByTestId("export-pdf-button")
      await expect(exportBtn).toBeVisible()

      const downloadPromise = page.waitForEvent("download")
      await exportBtn.click()
      const download = await downloadPromise

      expect(download.suggestedFilename()).toContain("CV")
    })
  })
})
