import { BrowserContext, expect, test } from "@playwright/test"

async function getUserIdFromCookies(context: BrowserContext): Promise<string> {
  const cookies = await context.cookies()
  const tokenCookie = cookies.find((c) => c.name === "access_token")
  if (!tokenCookie) {
    throw new Error("access_token cookie not found")
  }
  const payloadBase64 = tokenCookie.value.split(".")[1]
  const payloadJson = Buffer.from(payloadBase64, "base64").toString("utf-8")
  const payload = JSON.parse(payloadJson) as { sub: number | string }
  return String(payload.sub)
}

test.describe("CV Preview page - employee", () => {
  test.use({ storageState: "playwright/.auth/user.json" })

  test.describe("Own CV Preview", () => {
    test.beforeEach(async ({ page, context }) => {
      const userId = await getUserIdFromCookies(context)
      await page.goto(`/users/${userId}/cvs`)
      const table = page.getByTestId("cvs-table")
      await expect(table).toBeVisible()

      // Setup: Check if employee has at least one CV
      const employeeEmail = "employee@test.com"
      const hasOwnCv =
        (await table.locator("tr", { hasText: employeeEmail }).count()) > 0

      if (!hasOwnCv) {
        const createBtn = page.getByTestId("create-cv-button")
        await expect(createBtn).toBeVisible()
        await page.waitForTimeout(1000)
        await createBtn.click()
        await expect(page.getByRole("dialog")).toBeVisible()

        await page.locator('input[id="name"]').fill("Autogenerated Employee CV")
        await page
          .locator('input[id="education"]')
          .fill("Autogenerated Education")
        await page
          .locator('textarea[id="description"]')
          .fill("Autogenerated Description")
        await page.getByTestId("dialog-submit-button").click()

        // Wait for success toast
        const successToast = page
          .locator("[data-sonner-toast] [data-title]")
          .filter({ hasText: "CV created successfully!" })
        await expect(successToast).toBeVisible()
        await expect(page.getByRole("dialog")).toBeHidden()
      }

      // Navigate to the own CV's preview page via details tab
      const ownRow = page
        .locator("tr")
        .filter({ hasText: employeeEmail })
        .first()
      await expect(ownRow).toBeVisible()
      await page.waitForTimeout(1000)
      await ownRow.getByTestId("row-actions-trigger").click()
      await page.getByTestId("row-action-view").click()
      await expect(page).toHaveURL(/\/cvs\/.+/)

      // Click Preview tab
      await page
        .getByRole("main")
        .getByRole("link", { name: "Preview" })
        .click()
      await expect(page).toHaveURL(/\/cvs\/.+\/preview/)
    })

    test("Should display own CV preview and allow downloading PDF", async ({
      page,
    }) => {
      // 1. Verify CV Preview layout elements are visible
      await expect(page.locator("#cv-preview")).toBeVisible()

      // Verify header info is visible and has text
      const nameHeading = page.locator("#cv-preview h2").first()
      await expect(nameHeading).toBeVisible()
      await expect(nameHeading).not.toBeEmpty()

      // 2. Verify Export PDF button is present and click it to download
      const exportBtn = page.getByTestId("export-pdf-button")
      await expect(exportBtn).toBeVisible()

      const downloadPromise = page.waitForEvent("download")
      await exportBtn.click()
      const download = await downloadPromise

      // Assert suggested filename matches
      expect(download.suggestedFilename()).toContain("CV")
    })
  })

  test.describe("Other CV Preview", () => {
    test("Should allow employee to view and download other user's CV preview", async ({
      page,
      context,
    }) => {
      const userId = await getUserIdFromCookies(context)
      const otherUserId = userId === "630" ? "629" : "630"
      await page.goto(`/users/${otherUserId}/cvs`)
      await expect(page.getByTestId("cvs-table")).toBeVisible()

      const directViewLink = page.getByTestId("row-direct-view").first()

      if (await directViewLink.isVisible()) {
        await directViewLink.click()
        await expect(page).toHaveURL(/\/cvs\/.+/)

        // Click Preview tab
        await page
          .getByRole("main")
          .getByRole("link", { name: "Preview" })
          .click()
        await expect(page).toHaveURL(/\/cvs\/.+\/preview/)

        // Verify other's CV Preview layout is visible
        await expect(page.locator("#cv-preview")).toBeVisible()

        // Verify PDF Export works for other's CV too
        const exportBtn = page.getByTestId("export-pdf-button")
        await expect(exportBtn).toBeVisible()

        const downloadPromise = page.waitForEvent("download")
        await exportBtn.click()
        const download = await downloadPromise

        expect(download.suggestedFilename()).toContain("CV")
      }
    })
  })
})
